algoritmo "CONTAGEM 5X"
// Função : Estrutura Repira Ate
// Autor : Marcos Fernando Borges
// Data : 25/07/2023
// Seção de Declarações 

var
cont: inteiro

inicio
// Seção de Comandos 

Escreval (" ------------------------- ")
Escreval (" ESTRUTURA REPITA - ATE 5X ")
Escreval (" ------------------------- ")
Escreval ("")


         cont <- 1

         Repita
            Escreva (cont , "...")
            cont <- (cont + 1)
         Ate (cont > 5)


Escreval ("")

fimalgoritmo
