algoritmo "CONTADOR <= 10"
// Função : Estrutura Enquanto
// Autor : Marcos Fernando Borges
// Data : 20/07/2023
// Seção de Declarações 

var
contador: inteiro

inicio
// Seção de Comandos 

Escreval (" --------------- ")
Escreval (" CONTADOR ATE 10 ")
Escreval (" --------------- ")
Escreval ("")

contador <- 0

         Enquanto (contador <= 10) faca
            Escreval (contador)
            contador <- (contador + 1)
         FimEnquanto

Escreval ("")

fimalgoritmo
