Algoritmo "Primeiro Programa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Olá Mundo!
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 12/05/2023

Var
// Seção de Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval ("Olá Mundo!")
Escreval ("Me livrei da Maldição!")


Fimalgoritmo